export const COMENZAR_DESCARGA_ITEMS = 'COMENZAR_DESCARGA_ITEMS';
export const DESCARGA_ITEMS_EXITO = 'DESCARGA_ITEMS_EXITO';
export const DESCARGA_ITEMS_ERROR = 'DESCARGA_ITEMS_ERROR';
export const LIMPIAR_ITEMS = 'LIMPIAR_ITEMS'

export const COMENZAR_DESCARGA_COMICS = 'COMENZAR_DESCARGA_COMICS';
export const DESCARGA_COMICS_EXITO = 'DESCARGA_COMICS_EXITO ';
export const DESCARGA_COMICS_ERROR = 'DESCARGA_COMICS_ERROR';

export const COMENZAR_DESCARGA_STORIES = 'COMENZAR_DESCARGA_STORIES';
export const DESCARGA_STORIES_EXITO = 'DESCARGA_STORIES_EXITO';
export const DESCARGA_STORIES_ERROR = 'DESCARGA_STORIES_ERROR';

export const COMENZAR_DESCARGA_DATA = 'COMENZAR_DESCARGA_DATA';
export const DESCARGA_DATA_EXITO = 'DESCARGA_DATA_EXITO';
export const DESCARGA_DATA_ERROR = 'DESCARGA_DATA_ERROR';
export const LIMPIAR_DATA = 'LIMPIAR_DATA';
